APP_ENV: prod
APP_DEBUG: false

AWS_ACCOUNT_REGION: us-east-1
AWS_ACCOUNT_PROFILE: slsProdProfile

AWS_LAMBDA_TIMEOUT: 3
AWS_LAMBDA_MEMORY_SIZE: 128

AWS_LOG_RETENTION_DAYS: 7

AWS_APIGATEWAY_SECRET_KEY:
