ping:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test
  timeout: 1
  reservedConcurrency: 3
  events:
    - http:
        path: ping
        method: get
        private: false
        cors: ${self:custom.http.cors}

pingAuth:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test with authentication
  timeout: 1
  reservedConcurrency: 3
  events:
    - http:
        path: ping/auth
        method: get
        private: true
        cors: ${self:custom.http.cors}
