service:
  name: my-new-api-service

plugins:
  - serverless-webpack
  - serverless-api-compression
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-plugin-log-retention

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: ${self:provider.environment.AWS_LAMBDA_MEMORY_SIZE, 128}
  timeout: ${self:provider.environment.AWS_LAMBDA_TIMEOUT, 3}
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:provider.stackName}
  stage: ${opt:stage, 'local'}
  profile: ${self:provider.environment.AWS_ACCOUNT_PROFILE}
  region: ${opt:region, self:provider.environment.AWS_ACCOUNT_REGION, 'us-west-1'}
  environment: ${file(./environments/${self:provider.stage}.yml)}
  apiKeys:
    - usagePlan:
      - name: ${self:provider.stackName}-apiKey
        value: ${self:provider.environment.AWS_APIGATEWAY_SECRET_KEY}
  usagePlan:
    - usagePlan:
  stackTags:
    SITE: shared
    PRODUCT: ${self:service}
    STAGE: ${self:provider.stage}

custom:
  path:
    app: src/app
    functions: src/functions
    resources: src/resources
  serverless-offline:
    port: 8181
  webpack:
    packager: 'yarn'
  logRetentionInDays: ${self:provider.environment.AWS_LOG_RETENTION_DAYS, 7}
  contentEncoding:
    contentCompression: ${self:provider.environment.AWS_APIGATEWAY_COMPRESSION_MAX_BYTES, 100}
  http:
    cors: ${file(src/utils/cors.yml)}

# Add all the functions here
functions:
  - ${file(${self:custom.path.functions}/service.yml)}

# Add all the additional resources here
resources:
  #- ${file(${self:custom.path.resources}/service.yml)}