Resources:
  PingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:provider.stackName}-pingQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 43200 # 12h
      RedrivePolicy:
        deadLetterTargetArn:
          'Fn::GetAtt':
            - PingQueueDeadLetterQueue
            - Arn
        maxReceiveCount: 3

  PingQueueDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:provider.stackName}-pingQueueDLQ
      MessageRetentionPeriod: 43200 # 12h
